# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.api.users_api import UsersApi  # noqa: E501
from dupr_prod.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_provisional_rating_using_post(self):
        """Test case for create_user_provisional_rating_using_post

        Set the provisional rating for a player  # noqa: E501
        """
        pass

    def test_delete_user_provisional_rating_using_delete(self):
        """Test case for delete_user_provisional_rating_using_delete

        Delete the provisional rating for a player  # noqa: E501
        """
        pass

    def test_get_club_membership_by_dupr_id_using_get(self):
        """Test case for get_club_membership_by_dupr_id_using_get

        Retrieve the club membership for a user by DUPR Id  # noqa: E501
        """
        pass

    def test_get_user_provisional_rating_using_post(self):
        """Test case for get_user_provisional_rating_using_post

        Get the provisional rating for a player  # noqa: E501
        """
        pass

    def test_invite_user_using_post(self):
        """Test case for invite_user_using_post

        Pre-generate a dupr ID and invite a user to join  # noqa: E501
        """
        pass

    def test_update_user_provisional_rating_using_post(self):
        """Test case for update_user_provisional_rating_using_post

        Set the provisional rating for a player  # noqa: E501
        """
        pass

    def test_user_detail_using_get(self):
        """Test case for user_detail_using_get

        User Info  # noqa: E501
        """
        pass

    def test_user_search_using_post(self):
        """Test case for user_search_using_post

        User Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
