# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.api.match_api import MatchApi  # noqa: E501
from dupr_prod.rest import ApiException


class TestMatchApi(unittest.TestCase):
    """MatchApi unit test stubs"""

    def setUp(self):
        self.api = MatchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_match_using_delete(self):
        """Test case for delete_match_using_delete

        Delete Match  # noqa: E501
        """
        pass

    def test_save_match_in_bulk_using_post(self):
        """Test case for save_match_in_bulk_using_post

        Create Match in Bulk  # noqa: E501
        """
        pass

    def test_save_match_using_post(self):
        """Test case for save_match_using_post

        Create Match  # noqa: E501
        """
        pass

    def test_search_match_history_using_post(self):
        """Test case for search_match_history_using_post

        Get Match History  # noqa: E501
        """
        pass

    def test_update_match_using_post(self):
        """Test case for update_match_using_post

        Update a match  # noqa: E501
        """
        pass

    def test_view_match_using_get(self):
        """Test case for view_match_using_get

        viewMatch  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
