# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.api.api_registration_api import ApiRegistrationApi  # noqa: E501
from dupr_prod.rest import ApiException


class TestApiRegistrationApi(unittest.TestCase):
    """ApiRegistrationApi unit test stubs"""

    def setUp(self):
        self.api = ApiRegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_using_get(self):
        """Test case for get_all_using_get

        getAll  # noqa: E501
        """
        pass

    def test_register_using_post(self):
        """Test case for register_using_post

        register  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
