# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.models.single_wrapper_of_external_user_detail_response import SingleWrapperOfExternalUserDetailResponse  # noqa: E501
from dupr_prod.rest import ApiException


class TestSingleWrapperOfExternalUserDetailResponse(unittest.TestCase):
    """SingleWrapperOfExternalUserDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleWrapperOfExternalUserDetailResponse(self):
        """Test SingleWrapperOfExternalUserDetailResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_prod.models.single_wrapper_of_external_user_detail_response.SingleWrapperOfExternalUserDetailResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
