# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.api.player_api import PlayerApi  # noqa: E501
from dupr_prod.rest import ApiException


class TestPlayerApi(unittest.TestCase):
    """PlayerApi unit test stubs"""

    def setUp(self):
        self.api = PlayerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_player_duprid_by_email_using_post(self):
        """Test case for get_player_duprid_by_email_using_post

        Get DUPR ID by Email  # noqa: E501
        """
        pass

    def test_get_rank_of_players_using_post(self):
        """Test case for get_rank_of_players_using_post

        Players Rating  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
