# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.models.external_update_match_request import ExternalUpdateMatchRequest  # noqa: E501
from dupr_prod.rest import ApiException


class TestExternalUpdateMatchRequest(unittest.TestCase):
    """ExternalUpdateMatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalUpdateMatchRequest(self):
        """Test ExternalUpdateMatchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_prod.models.external_update_match_request.ExternalUpdateMatchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
