# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.api.club_api import ClubApi  # noqa: E501
from dupr_prod.rest import ApiException


class TestClubApi(unittest.TestCase):
    """ClubApi unit test stubs"""

    def setUp(self):
        self.api = ClubApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_club_members_rating_using_post(self):
        """Test case for club_members_rating_using_post

        Club Members Rating  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
