# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_prod
from dupr_prod.api.player_rating_api import PlayerRatingApi  # noqa: E501
from dupr_prod.rest import ApiException


class TestPlayerRatingApi(unittest.TestCase):
    """PlayerRatingApi unit test stubs"""

    def setUp(self):
        self.api = PlayerRatingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_client_players_subscription_using_get(self):
        """Test case for get_client_players_subscription_using_get

        Fetch Players subscription by Client  # noqa: E501
        """
        pass

    def test_remove_player_subscription_using_delete(self):
        """Test case for remove_player_subscription_using_delete

        Removes players rating  # noqa: E501
        """
        pass

    def test_subscribe_player_rating_using_post(self):
        """Test case for subscribe_player_rating_using_post

        Subscribe players rating  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
