# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalDeleteMatchRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifier': 'str',
        'match_code': 'str'
    }

    attribute_map = {
        'identifier': 'identifier',
        'match_code': 'matchCode'
    }

    def __init__(self, identifier=None, match_code=None):  # noqa: E501
        """ExternalDeleteMatchRequest - a model defined in Swagger"""  # noqa: E501
        self._identifier = None
        self._match_code = None
        self.discriminator = None
        self.identifier = identifier
        self.match_code = match_code

    @property
    def identifier(self):
        """Gets the identifier of this ExternalDeleteMatchRequest.  # noqa: E501

        An unique identifier for this match  # noqa: E501

        :return: The identifier of this ExternalDeleteMatchRequest.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this ExternalDeleteMatchRequest.

        An unique identifier for this match  # noqa: E501

        :param identifier: The identifier of this ExternalDeleteMatchRequest.  # noqa: E501
        :type: str
        """
        if identifier is None:
            raise ValueError("Invalid value for `identifier`, must not be `None`")  # noqa: E501

        self._identifier = identifier

    @property
    def match_code(self):
        """Gets the match_code of this ExternalDeleteMatchRequest.  # noqa: E501

        An unique match code returned at time of creation  # noqa: E501

        :return: The match_code of this ExternalDeleteMatchRequest.  # noqa: E501
        :rtype: str
        """
        return self._match_code

    @match_code.setter
    def match_code(self, match_code):
        """Sets the match_code of this ExternalDeleteMatchRequest.

        An unique match code returned at time of creation  # noqa: E501

        :param match_code: The match_code of this ExternalDeleteMatchRequest.  # noqa: E501
        :type: str
        """
        if match_code is None:
            raise ValueError("Invalid value for `match_code`, must not be `None`")  # noqa: E501

        self._match_code = match_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalDeleteMatchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalDeleteMatchRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
