# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalUserDetailResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first_name': 'str',
        'full_name': 'str',
        'id': 'str',
        'last_name': 'str',
        'performance': 'ExternalUserPerformance',
        'ratings': 'object'
    }

    attribute_map = {
        'first_name': 'firstName',
        'full_name': 'fullName',
        'id': 'id',
        'last_name': 'lastName',
        'performance': 'performance',
        'ratings': 'ratings'
    }

    def __init__(self, first_name=None, full_name=None, id=None, last_name=None, performance=None, ratings=None):  # noqa: E501
        """ExternalUserDetailResponse - a model defined in Swagger"""  # noqa: E501
        self._first_name = None
        self._full_name = None
        self._id = None
        self._last_name = None
        self._performance = None
        self._ratings = None
        self.discriminator = None
        self.first_name = first_name
        self.full_name = full_name
        self.id = id
        self.last_name = last_name
        self.performance = performance
        self.ratings = ratings

    @property
    def first_name(self):
        """Gets the first_name of this ExternalUserDetailResponse.  # noqa: E501


        :return: The first_name of this ExternalUserDetailResponse.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this ExternalUserDetailResponse.


        :param first_name: The first_name of this ExternalUserDetailResponse.  # noqa: E501
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def full_name(self):
        """Gets the full_name of this ExternalUserDetailResponse.  # noqa: E501


        :return: The full_name of this ExternalUserDetailResponse.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this ExternalUserDetailResponse.


        :param full_name: The full_name of this ExternalUserDetailResponse.  # noqa: E501
        :type: str
        """
        if full_name is None:
            raise ValueError("Invalid value for `full_name`, must not be `None`")  # noqa: E501

        self._full_name = full_name

    @property
    def id(self):
        """Gets the id of this ExternalUserDetailResponse.  # noqa: E501


        :return: The id of this ExternalUserDetailResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExternalUserDetailResponse.


        :param id: The id of this ExternalUserDetailResponse.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def last_name(self):
        """Gets the last_name of this ExternalUserDetailResponse.  # noqa: E501


        :return: The last_name of this ExternalUserDetailResponse.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this ExternalUserDetailResponse.


        :param last_name: The last_name of this ExternalUserDetailResponse.  # noqa: E501
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def performance(self):
        """Gets the performance of this ExternalUserDetailResponse.  # noqa: E501


        :return: The performance of this ExternalUserDetailResponse.  # noqa: E501
        :rtype: ExternalUserPerformance
        """
        return self._performance

    @performance.setter
    def performance(self, performance):
        """Sets the performance of this ExternalUserDetailResponse.


        :param performance: The performance of this ExternalUserDetailResponse.  # noqa: E501
        :type: ExternalUserPerformance
        """
        if performance is None:
            raise ValueError("Invalid value for `performance`, must not be `None`")  # noqa: E501

        self._performance = performance

    @property
    def ratings(self):
        """Gets the ratings of this ExternalUserDetailResponse.  # noqa: E501


        :return: The ratings of this ExternalUserDetailResponse.  # noqa: E501
        :rtype: object
        """
        return self._ratings

    @ratings.setter
    def ratings(self, ratings):
        """Sets the ratings of this ExternalUserDetailResponse.


        :param ratings: The ratings of this ExternalUserDetailResponse.  # noqa: E501
        :type: object
        """
        if ratings is None:
            raise ValueError("Invalid value for `ratings`, must not be `None`")  # noqa: E501

        self._ratings = ratings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalUserDetailResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalUserDetailResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
