# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalMatchTeam(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'game1': 'int',
        'game2': 'int',
        'game3': 'int',
        'game4': 'int',
        'game5': 'int',
        'player1': 'str',
        'player2': 'str'
    }

    attribute_map = {
        'game1': 'game1',
        'game2': 'game2',
        'game3': 'game3',
        'game4': 'game4',
        'game5': 'game5',
        'player1': 'player1',
        'player2': 'player2'
    }

    def __init__(self, game1=None, game2=None, game3=None, game4=None, game5=None, player1=None, player2=None):  # noqa: E501
        """ExternalMatchTeam - a model defined in Swagger"""  # noqa: E501
        self._game1 = None
        self._game2 = None
        self._game3 = None
        self._game4 = None
        self._game5 = None
        self._player1 = None
        self._player2 = None
        self.discriminator = None
        self.game1 = game1
        if game2 is not None:
            self.game2 = game2
        if game3 is not None:
            self.game3 = game3
        if game4 is not None:
            self.game4 = game4
        if game5 is not None:
            self.game5 = game5
        self.player1 = player1
        if player2 is not None:
            self.player2 = player2

    @property
    def game1(self):
        """Gets the game1 of this ExternalMatchTeam.  # noqa: E501

        Team's Game 1 score  # noqa: E501

        :return: The game1 of this ExternalMatchTeam.  # noqa: E501
        :rtype: int
        """
        return self._game1

    @game1.setter
    def game1(self, game1):
        """Sets the game1 of this ExternalMatchTeam.

        Team's Game 1 score  # noqa: E501

        :param game1: The game1 of this ExternalMatchTeam.  # noqa: E501
        :type: int
        """
        if game1 is None:
            raise ValueError("Invalid value for `game1`, must not be `None`")  # noqa: E501

        self._game1 = game1

    @property
    def game2(self):
        """Gets the game2 of this ExternalMatchTeam.  # noqa: E501

        Team's Game 2 score  # noqa: E501

        :return: The game2 of this ExternalMatchTeam.  # noqa: E501
        :rtype: int
        """
        return self._game2

    @game2.setter
    def game2(self, game2):
        """Sets the game2 of this ExternalMatchTeam.

        Team's Game 2 score  # noqa: E501

        :param game2: The game2 of this ExternalMatchTeam.  # noqa: E501
        :type: int
        """

        self._game2 = game2

    @property
    def game3(self):
        """Gets the game3 of this ExternalMatchTeam.  # noqa: E501

        Team's Game 3 score  # noqa: E501

        :return: The game3 of this ExternalMatchTeam.  # noqa: E501
        :rtype: int
        """
        return self._game3

    @game3.setter
    def game3(self, game3):
        """Sets the game3 of this ExternalMatchTeam.

        Team's Game 3 score  # noqa: E501

        :param game3: The game3 of this ExternalMatchTeam.  # noqa: E501
        :type: int
        """

        self._game3 = game3

    @property
    def game4(self):
        """Gets the game4 of this ExternalMatchTeam.  # noqa: E501

        Team's Game 4 score  # noqa: E501

        :return: The game4 of this ExternalMatchTeam.  # noqa: E501
        :rtype: int
        """
        return self._game4

    @game4.setter
    def game4(self, game4):
        """Sets the game4 of this ExternalMatchTeam.

        Team's Game 4 score  # noqa: E501

        :param game4: The game4 of this ExternalMatchTeam.  # noqa: E501
        :type: int
        """

        self._game4 = game4

    @property
    def game5(self):
        """Gets the game5 of this ExternalMatchTeam.  # noqa: E501

        Team's Game 5 score  # noqa: E501

        :return: The game5 of this ExternalMatchTeam.  # noqa: E501
        :rtype: int
        """
        return self._game5

    @game5.setter
    def game5(self, game5):
        """Sets the game5 of this ExternalMatchTeam.

        Team's Game 5 score  # noqa: E501

        :param game5: The game5 of this ExternalMatchTeam.  # noqa: E501
        :type: int
        """

        self._game5 = game5

    @property
    def player1(self):
        """Gets the player1 of this ExternalMatchTeam.  # noqa: E501

        DUPR ID of player 1  # noqa: E501

        :return: The player1 of this ExternalMatchTeam.  # noqa: E501
        :rtype: str
        """
        return self._player1

    @player1.setter
    def player1(self, player1):
        """Sets the player1 of this ExternalMatchTeam.

        DUPR ID of player 1  # noqa: E501

        :param player1: The player1 of this ExternalMatchTeam.  # noqa: E501
        :type: str
        """
        if player1 is None:
            raise ValueError("Invalid value for `player1`, must not be `None`")  # noqa: E501

        self._player1 = player1

    @property
    def player2(self):
        """Gets the player2 of this ExternalMatchTeam.  # noqa: E501

        DUPR ID of player 2, in case of singles it can be null  # noqa: E501

        :return: The player2 of this ExternalMatchTeam.  # noqa: E501
        :rtype: str
        """
        return self._player2

    @player2.setter
    def player2(self, player2):
        """Sets the player2 of this ExternalMatchTeam.

        DUPR ID of player 2, in case of singles it can be null  # noqa: E501

        :param player2: The player2 of this ExternalMatchTeam.  # noqa: E501
        :type: str
        """

        self._player2 = player2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalMatchTeam, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalMatchTeam):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
