# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalRatingFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max': 'float',
        'min': 'float',
        'reliable': 'bool',
        'type': 'str'
    }

    attribute_map = {
        'max': 'max',
        'min': 'min',
        'reliable': 'reliable',
        'type': 'type'
    }

    def __init__(self, max=None, min=None, reliable=None, type=None):  # noqa: E501
        """ExternalRatingFilter - a model defined in Swagger"""  # noqa: E501
        self._max = None
        self._min = None
        self._reliable = None
        self._type = None
        self.discriminator = None
        self.max = max
        self.min = min
        if reliable is not None:
            self.reliable = reliable
        if type is not None:
            self.type = type

    @property
    def max(self):
        """Gets the max of this ExternalRatingFilter.  # noqa: E501

        Maximum value of user ratings can be up to 8.0  # noqa: E501

        :return: The max of this ExternalRatingFilter.  # noqa: E501
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this ExternalRatingFilter.

        Maximum value of user ratings can be up to 8.0  # noqa: E501

        :param max: The max of this ExternalRatingFilter.  # noqa: E501
        :type: float
        """
        if max is None:
            raise ValueError("Invalid value for `max`, must not be `None`")  # noqa: E501

        self._max = max

    @property
    def min(self):
        """Gets the min of this ExternalRatingFilter.  # noqa: E501

        Minimum value of user ratings can be down to 2.0  # noqa: E501

        :return: The min of this ExternalRatingFilter.  # noqa: E501
        :rtype: float
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this ExternalRatingFilter.

        Minimum value of user ratings can be down to 2.0  # noqa: E501

        :param min: The min of this ExternalRatingFilter.  # noqa: E501
        :type: float
        """
        if min is None:
            raise ValueError("Invalid value for `min`, must not be `None`")  # noqa: E501

        self._min = min

    @property
    def reliable(self):
        """Gets the reliable of this ExternalRatingFilter.  # noqa: E501

        Ratings should be reliable or not, by default null which means it is not considered  # noqa: E501

        :return: The reliable of this ExternalRatingFilter.  # noqa: E501
        :rtype: bool
        """
        return self._reliable

    @reliable.setter
    def reliable(self, reliable):
        """Sets the reliable of this ExternalRatingFilter.

        Ratings should be reliable or not, by default null which means it is not considered  # noqa: E501

        :param reliable: The reliable of this ExternalRatingFilter.  # noqa: E501
        :type: bool
        """

        self._reliable = reliable

    @property
    def type(self):
        """Gets the type of this ExternalRatingFilter.  # noqa: E501

        Type of ratings to apply min and max values, one of the value from following array.  # noqa: E501

        :return: The type of this ExternalRatingFilter.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ExternalRatingFilter.

        Type of ratings to apply min and max values, one of the value from following array.  # noqa: E501

        :param type: The type of this ExternalRatingFilter.  # noqa: E501
        :type: str
        """
        allowed_values = ["DOUBLES", "SINGLES"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalRatingFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalRatingFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
