# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalSearchRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filters': 'ExternalSearchFilter',
        'limit': 'int',
        'offset': 'int',
        'query': 'str'
    }

    attribute_map = {
        'filters': 'filters',
        'limit': 'limit',
        'offset': 'offset',
        'query': 'query'
    }

    def __init__(self, filters=None, limit=None, offset=None, query=None):  # noqa: E501
        """ExternalSearchRequest - a model defined in Swagger"""  # noqa: E501
        self._filters = None
        self._limit = None
        self._offset = None
        self._query = None
        self.discriminator = None
        if filters is not None:
            self.filters = filters
        self.limit = limit
        self.offset = offset
        self.query = query

    @property
    def filters(self):
        """Gets the filters of this ExternalSearchRequest.  # noqa: E501


        :return: The filters of this ExternalSearchRequest.  # noqa: E501
        :rtype: ExternalSearchFilter
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """Sets the filters of this ExternalSearchRequest.


        :param filters: The filters of this ExternalSearchRequest.  # noqa: E501
        :type: ExternalSearchFilter
        """

        self._filters = filters

    @property
    def limit(self):
        """Gets the limit of this ExternalSearchRequest.  # noqa: E501

        Number of results in a page  # noqa: E501

        :return: The limit of this ExternalSearchRequest.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ExternalSearchRequest.

        Number of results in a page  # noqa: E501

        :param limit: The limit of this ExternalSearchRequest.  # noqa: E501
        :type: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this ExternalSearchRequest.  # noqa: E501

        Starting offset to paginate results  # noqa: E501

        :return: The offset of this ExternalSearchRequest.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ExternalSearchRequest.

        Starting offset to paginate results  # noqa: E501

        :param offset: The offset of this ExternalSearchRequest.  # noqa: E501
        :type: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501

        self._offset = offset

    @property
    def query(self):
        """Gets the query of this ExternalSearchRequest.  # noqa: E501

        User full or partial name to get details  # noqa: E501

        :return: The query of this ExternalSearchRequest.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this ExternalSearchRequest.

        User full or partial name to get details  # noqa: E501

        :param query: The query of this ExternalSearchRequest.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalSearchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalSearchRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
