# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlayersSortedRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dupr_ids': 'list[str]',
        'sort_by': 'str'
    }

    attribute_map = {
        'dupr_ids': 'duprIds',
        'sort_by': 'sortBy'
    }

    def __init__(self, dupr_ids=None, sort_by=None):  # noqa: E501
        """PlayersSortedRequest - a model defined in Swagger"""  # noqa: E501
        self._dupr_ids = None
        self._sort_by = None
        self.discriminator = None
        self.dupr_ids = dupr_ids
        self.sort_by = sort_by

    @property
    def dupr_ids(self):
        """Gets the dupr_ids of this PlayersSortedRequest.  # noqa: E501


        :return: The dupr_ids of this PlayersSortedRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._dupr_ids

    @dupr_ids.setter
    def dupr_ids(self, dupr_ids):
        """Sets the dupr_ids of this PlayersSortedRequest.


        :param dupr_ids: The dupr_ids of this PlayersSortedRequest.  # noqa: E501
        :type: list[str]
        """
        if dupr_ids is None:
            raise ValueError("Invalid value for `dupr_ids`, must not be `None`")  # noqa: E501

        self._dupr_ids = dupr_ids

    @property
    def sort_by(self):
        """Gets the sort_by of this PlayersSortedRequest.  # noqa: E501


        :return: The sort_by of this PlayersSortedRequest.  # noqa: E501
        :rtype: str
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by):
        """Sets the sort_by of this PlayersSortedRequest.


        :param sort_by: The sort_by of this PlayersSortedRequest.  # noqa: E501
        :type: str
        """
        if sort_by is None:
            raise ValueError("Invalid value for `sort_by`, must not be `None`")  # noqa: E501

        self._sort_by = sort_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlayersSortedRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlayersSortedRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
