# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateProvisionalRatingRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dupr_id': 'str',
        'provisional_doubles_rating': 'float',
        'provisional_singles_rating': 'float'
    }

    attribute_map = {
        'dupr_id': 'duprId',
        'provisional_doubles_rating': 'provisionalDoublesRating',
        'provisional_singles_rating': 'provisionalSinglesRating'
    }

    def __init__(self, dupr_id=None, provisional_doubles_rating=None, provisional_singles_rating=None):  # noqa: E501
        """UpdateProvisionalRatingRequest - a model defined in Swagger"""  # noqa: E501
        self._dupr_id = None
        self._provisional_doubles_rating = None
        self._provisional_singles_rating = None
        self.discriminator = None
        self.dupr_id = dupr_id
        if provisional_doubles_rating is not None:
            self.provisional_doubles_rating = provisional_doubles_rating
        if provisional_singles_rating is not None:
            self.provisional_singles_rating = provisional_singles_rating

    @property
    def dupr_id(self):
        """Gets the dupr_id of this UpdateProvisionalRatingRequest.  # noqa: E501


        :return: The dupr_id of this UpdateProvisionalRatingRequest.  # noqa: E501
        :rtype: str
        """
        return self._dupr_id

    @dupr_id.setter
    def dupr_id(self, dupr_id):
        """Sets the dupr_id of this UpdateProvisionalRatingRequest.


        :param dupr_id: The dupr_id of this UpdateProvisionalRatingRequest.  # noqa: E501
        :type: str
        """
        if dupr_id is None:
            raise ValueError("Invalid value for `dupr_id`, must not be `None`")  # noqa: E501

        self._dupr_id = dupr_id

    @property
    def provisional_doubles_rating(self):
        """Gets the provisional_doubles_rating of this UpdateProvisionalRatingRequest.  # noqa: E501


        :return: The provisional_doubles_rating of this UpdateProvisionalRatingRequest.  # noqa: E501
        :rtype: float
        """
        return self._provisional_doubles_rating

    @provisional_doubles_rating.setter
    def provisional_doubles_rating(self, provisional_doubles_rating):
        """Sets the provisional_doubles_rating of this UpdateProvisionalRatingRequest.


        :param provisional_doubles_rating: The provisional_doubles_rating of this UpdateProvisionalRatingRequest.  # noqa: E501
        :type: float
        """

        self._provisional_doubles_rating = provisional_doubles_rating

    @property
    def provisional_singles_rating(self):
        """Gets the provisional_singles_rating of this UpdateProvisionalRatingRequest.  # noqa: E501


        :return: The provisional_singles_rating of this UpdateProvisionalRatingRequest.  # noqa: E501
        :rtype: float
        """
        return self._provisional_singles_rating

    @provisional_singles_rating.setter
    def provisional_singles_rating(self, provisional_singles_rating):
        """Sets the provisional_singles_rating of this UpdateProvisionalRatingRequest.


        :param provisional_singles_rating: The provisional_singles_rating of this UpdateProvisionalRatingRequest.  # noqa: E501
        :type: float
        """

        self._provisional_singles_rating = provisional_singles_rating

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateProvisionalRatingRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateProvisionalRatingRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
