# coding: utf-8

"""
    DUPR APIs

    External RESTful APIs to access DUPR ratings, users and provide matches.  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WinLossCount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'loss': 'int',
        'total': 'int',
        'win': 'int'
    }

    attribute_map = {
        'loss': 'loss',
        'total': 'total',
        'win': 'win'
    }

    def __init__(self, loss=None, total=None, win=None):  # noqa: E501
        """WinLossCount - a model defined in Swagger"""  # noqa: E501
        self._loss = None
        self._total = None
        self._win = None
        self.discriminator = None
        self.loss = loss
        self.total = total
        self.win = win

    @property
    def loss(self):
        """Gets the loss of this WinLossCount.  # noqa: E501


        :return: The loss of this WinLossCount.  # noqa: E501
        :rtype: int
        """
        return self._loss

    @loss.setter
    def loss(self, loss):
        """Sets the loss of this WinLossCount.


        :param loss: The loss of this WinLossCount.  # noqa: E501
        :type: int
        """
        if loss is None:
            raise ValueError("Invalid value for `loss`, must not be `None`")  # noqa: E501

        self._loss = loss

    @property
    def total(self):
        """Gets the total of this WinLossCount.  # noqa: E501


        :return: The total of this WinLossCount.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this WinLossCount.


        :param total: The total of this WinLossCount.  # noqa: E501
        :type: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def win(self):
        """Gets the win of this WinLossCount.  # noqa: E501


        :return: The win of this WinLossCount.  # noqa: E501
        :rtype: int
        """
        return self._win

    @win.setter
    def win(self, win):
        """Sets the win of this WinLossCount.


        :param win: The win of this WinLossCount.  # noqa: E501
        :type: int
        """
        if win is None:
            raise ValueError("Invalid value for `win`, must not be `None`")  # noqa: E501

        self._win = win

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WinLossCount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WinLossCount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
